apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: k01zo8viw-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe:e9dfa303ec6821a3c200941791dda2ec699ee397@sha256:abf4b0ee1d9626cbccbf437f27c4a1e859f54dd699d463c4931735b782a3c89b
          name: container-image
